export const repositories: ['401', '403', 'lotto'] = ['401', '403', 'lotto']

export enum CountActions {
	UPDATE_REPO = 'UPDATE_REPO',
	UPDATE_COUTNER = 'UPDATE_COUTNER',
	UPDATE_SUPERVISOR = 'UPDATE_SUPERVISOR',
	UPDATE_TIME = 'UPDATE_TIME',
	UPDATE_BAG = 'UPDATE_BAG',
	UPDATE_LOOSE = 'UPDATE_LOOSE',
	UPDATE_NOTES = 'UPDATE_NOTES',
}