enum ActionTypes {
	COUNTS_DATA_WRITE_ALL = 'COUNTS_DATA_WRITE_ALL',
	COUNTS_DATA_UPDATE_SINGLE = 'COUNTS_DATA_UPDATE_SINGLE',
	COUNTS_DATA_WRITE_SINGLE = 'COUNTS_DATA_WRITE_SINGLE',

	UI_FLASH_WRITE_ONE = 'UI_FLASH_WRITE_ONE',
	UI_FLASH_REMOVE_ONE = 'UI_FLASH_REMOVE_ONE',
}

export default ActionTypes