enum ActionTypes {
	COUNTS_DATA_WRITE_ALL = 'COUNTS_DATA_WRITE_ALL',
	COUNTS_DATA_WRITE_MULTIPLE = 'COUNTS_DATA_WRITE_MULTIPLE',
	COUNTS_DATA_UPDATE_SINGLE = 'COUNTS_DATA_UPDATE_SINGLE',
	COUNTS_DATA_WRITE_SINGLE = 'COUNTS_DATA_WRITE_SINGLE',
	COUNTS_SERVER_TOTAL_WRITE = 'COUNTS_SERVER_TOTAL_WRITE',

	UI_FLASH_WRITE_ONE = 'UI_FLASH_WRITE_ONE',
	UI_FLASH_REMOVE_ONE = 'UI_FLASH_REMOVE_ONE',

	AUTH_USERS_WRITE_ALL = 'AUTH_USERS_WRITE_ALL',
	AUTH_PARTNER_WRITE_ALL = 'AUTH_PARTNER_WRITE_ALL',

	REPOSITORIES_WRITE_ALL = 'REPOSITORIES_WRITE_ALL',
}

export default ActionTypes