enum ActionTypes {
	COUNTS_DATA_WRITE_ALL = 'COUNTS_DATA_WRITE_ALL',
	COUNTS_DATA_UPDATE_SINGLE = 'COUNTS_DATA_UPDATE_SINGLE',
	COUNTS_DATA_WRITE_SINGLE = 'COUNTS_DATA_WRITE_SINGLE',
}

export default ActionTypes